# Generated by Django 4.2.1 on 2023-06-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistaPubli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obras', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidop', models.CharField(max_length=50)),
                ('apellidom', models.CharField(max_length=50)),
                ('nombreU', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.BooleanField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArt', models.CharField(max_length=50)),
                ('tipO', models.BooleanField()),
                ('nombreO', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('valorO', models.IntegerField()),
                ('fechaO', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('artistaPubli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appweb.artistapubli')),
            ],
        ),
    ]
