# Generated by Django 4.2.1 on 2023-06-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_alter_contacto_comuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='comuna',
            new_name='tipo_comuna',
        ),
    ]
