# Generated by Django 4.2.1 on 2023-06-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_rename_comuna_contacto_tipo_comuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistapubli',
            old_name='obras',
            new_name='nombreO',
        ),
    ]
