# Generated by Django 4.2.1 on 2023-06-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_alter_contacto_tipo_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tipO',
            field=models.CharField(max_length=50),
        ),
    ]
