# Generated by Django 4.2.1 on 2023-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_obra_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('descripcionPersonal', models.CharField(max_length=200)),
                ('experienciaLaboral', models.CharField(max_length=200)),
                ('idiomas', models.CharField(max_length=200)),
                ('foto', models.ImageField(null=True, upload_to='obra')),
                ('CV', models.ImageField(null=True, upload_to='obra')),
            ],
        ),
    ]
