# Generated by Django 4.2.1 on 2023-07-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_rename_artistapubli_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='artista',
        ),
    ]
